export const MAIN = {
  LOGIN_POPUP_HANDLER: 'LOGIN_POPUP_HANDLER',
};

export const USER = {
  REGISTER_SUCCESSFULLY_HANDLER: 'REGISTER_SUCCESSFULLY_HANDLER',
  LOGIN_SUCCESSFULLY_HANDLER: 'LOGIN_SUCCESSFULLY_HANDLER',
  LOGOUT_HANDLER: 'LOGOUT_HANDLER'
};