export const MAIN = {
  LOGIN_POPUP_HANDLER: 'MAIN.LOGIN_POPUP_HANDLER',
  OPEN_POLICY_MODAL: 'MAIN.OPEN_POLICY_MODAL',
};

export const USER = {
  REGISTER_SUCCESSFULLY_HANDLER: 'USER.REGISTER_SUCCESSFULLY_HANDLER',
  LOGIN_SUCCESSFULLY_HANDLER: 'USER.LOGIN_SUCCESSFULLY_HANDLER',
  LOGOUT_HANDLER: 'USER.LOGOUT_HANDLER'
};